### ISSUE TITLE
Glenelg Shire Council data not rendering name properly?

### ISSUE THREAD

**Issue by CloCkWeRX** [OKFNau/binsmap#8]
http://data.gov.au/dataset/glenelg-waste-collection-2015-16/resource/f5e8a03d-ed7b-4607-84eb-3643a8f9b42d _looks_ like it has all of the right attributes, but for some reason the data on openbinmap.org renders 'null' instead of name, etc.

![image](https://cloud.githubusercontent.com/assets/365751/10726094/6ec90ab2-7c20-11e5-8a81-20536331a144.png)

I can't really tell if the data is right/transform is right - master doesn't seem to have commits adding this data recently

**Comment by CloCkWeRX** [comment]
@stevage - any chance you can push the commits you used to add this one; maybe I can figure out the bug with the transformation

**Comment by stevage** [comment]
Thanks @CloCkWeRX - sorry, I don't think I saw this notification. Fixed now.
